### PR TITLE
Python log parser update

### PR DESCRIPTION
**Pull request by matteobarbera**
Translated the Matlab scripts in new_matlab to python3. The log file can now be parsed using the message.xml, so that ABI messages are always up to date. The approach is almost exactly the same as the one used in new_matlab.

The output is a modified Python dictionary, with its key/value pair being accessible with the same syntax of a Matlab struct. Both of these will work:

- d["key"] = value
- d.key = value

### CODE REVIEW

**Comment by fvantienen** [comment]
Maybe add an example on how to use it.

**Comment by matteobarbera** [comment]
The example added demonstrates how to make a few plots from a parsed .data file, showcasing some basic numpy and matplotlib features

**Comment by fvantienen** [comment]
Thanks @matteobarbera! One last thing is that the matlab script parses the `.log` file and extracts the `messages.xml` file from it, such that the version matches exactly. If you do not do this, it could lead to problems opening older log files with different messages. Could you also implement this?

The parsing using the `messages.xml` file from the paparazzi folder is only used when the `.log` file is not present.

**Comment by matteobarbera** [comment]
@fvantienen I added the functionality you asked for, I had to use BeautifulSoup instead of Python's standard ElementTree because standard xml parsers can't immediately deal with the characters && found in the .log file.

I also slightly changed the functionality of splitlog from the Matlab implementation. The function I wrote does not return the aircraft information, but only optionally generates the ac.xml. Looking at the Matlab implementation, that part of the function was never used, and I couldn't immediately think of a reason to implement it, but please correct me if I'm wrong!

**Pull request merged**
